# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalkulator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leWyswietlacz = QtWidgets.QLineEdit(self.centralwidget)
        self.leWyswietlacz.setGeometry(QtCore.QRect(20, 10, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.leWyswietlacz.setFont(font)
        self.leWyswietlacz.setReadOnly(True)
        self.leWyswietlacz.setObjectName("leWyswietlacz")
        self.pb0 = QtWidgets.QPushButton(self.centralwidget)
        self.pb0.setGeometry(QtCore.QRect(20, 170, 161, 31))
        self.pb0.setIconSize(QtCore.QSize(8, 8))
        self.pb0.setObjectName("pb0")
        self.pbWynik = QtWidgets.QPushButton(self.centralwidget)
        self.pbWynik.setGeometry(QtCore.QRect(180, 170, 81, 31))
        self.pbWynik.setIconSize(QtCore.QSize(8, 8))
        self.pbWynik.setObjectName("pbWynik")
        self.pbMnozenie = QtWidgets.QPushButton(self.centralwidget)
        self.pbMnozenie.setGeometry(QtCore.QRect(260, 111, 81, 31))
        self.pbMnozenie.setIconSize(QtCore.QSize(8, 8))
        self.pbMnozenie.setObjectName("pbMnozenie")
        self.pbDzielenie = QtWidgets.QPushButton(self.centralwidget)
        self.pbDzielenie.setGeometry(QtCore.QRect(260, 82, 81, 31))
        self.pbDzielenie.setIconSize(QtCore.QSize(8, 8))
        self.pbDzielenie.setObjectName("pbDzielenie")
        self.pbDodaj = QtWidgets.QPushButton(self.centralwidget)
        self.pbDodaj.setGeometry(QtCore.QRect(260, 140, 81, 31))
        self.pbDodaj.setIconSize(QtCore.QSize(8, 8))
        self.pbDodaj.setObjectName("pbDodaj")
        self.pbOdejmij = QtWidgets.QPushButton(self.centralwidget)
        self.pbOdejmij.setGeometry(QtCore.QRect(260, 170, 81, 31))
        self.pbOdejmij.setIconSize(QtCore.QSize(8, 8))
        self.pbOdejmij.setObjectName("pbOdejmij")
        self.pbKropka = QtWidgets.QPushButton(self.centralwidget)
        self.pbKropka.setGeometry(QtCore.QRect(20, 200, 81, 31))
        self.pbKropka.setIconSize(QtCore.QSize(8, 8))
        self.pbKropka.setObjectName("pbKropka")
        self.pbClear = QtWidgets.QPushButton(self.centralwidget)
        self.pbClear.setGeometry(QtCore.QRect(100, 200, 81, 31))
        self.pbClear.setIconSize(QtCore.QSize(8, 8))
        self.pbClear.setObjectName("pbClear")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 80, 239, 91))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pb7 = QtWidgets.QPushButton(self.widget)
        self.pb7.setIconSize(QtCore.QSize(8, 8))
        self.pb7.setObjectName("pb7")
        self.gridLayout.addWidget(self.pb7, 0, 0, 1, 1)
        self.pb8 = QtWidgets.QPushButton(self.widget)
        self.pb8.setIconSize(QtCore.QSize(8, 8))
        self.pb8.setObjectName("pb8")
        self.gridLayout.addWidget(self.pb8, 0, 1, 1, 1)
        self.pb9 = QtWidgets.QPushButton(self.widget)
        self.pb9.setIconSize(QtCore.QSize(8, 8))
        self.pb9.setObjectName("pb9")
        self.gridLayout.addWidget(self.pb9, 0, 2, 1, 1)
        self.pb4 = QtWidgets.QPushButton(self.widget)
        self.pb4.setIconSize(QtCore.QSize(8, 8))
        self.pb4.setObjectName("pb4")
        self.gridLayout.addWidget(self.pb4, 1, 0, 1, 1)
        self.pb5 = QtWidgets.QPushButton(self.widget)
        self.pb5.setIconSize(QtCore.QSize(8, 8))
        self.pb5.setObjectName("pb5")
        self.gridLayout.addWidget(self.pb5, 1, 1, 1, 1)
        self.pb6 = QtWidgets.QPushButton(self.widget)
        self.pb6.setIconSize(QtCore.QSize(8, 8))
        self.pb6.setObjectName("pb6")
        self.gridLayout.addWidget(self.pb6, 1, 2, 1, 1)
        self.pb1 = QtWidgets.QPushButton(self.widget)
        self.pb1.setIconSize(QtCore.QSize(8, 8))
        self.pb1.setObjectName("pb1")
        self.gridLayout.addWidget(self.pb1, 2, 0, 1, 1)
        self.pb2 = QtWidgets.QPushButton(self.widget)
        self.pb2.setIconSize(QtCore.QSize(8, 8))
        self.pb2.setObjectName("pb2")
        self.gridLayout.addWidget(self.pb2, 2, 1, 1, 1)
        self.pb3 = QtWidgets.QPushButton(self.widget)
        self.pb3.setIconSize(QtCore.QSize(8, 8))
        self.pb3.setObjectName("pb3")
        self.gridLayout.addWidget(self.pb3, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kalkulator"))
        self.pb0.setText(_translate("MainWindow", "0"))
        self.pbWynik.setText(_translate("MainWindow", "="))
        self.pbMnozenie.setText(_translate("MainWindow", "*"))
        self.pbDzielenie.setText(_translate("MainWindow", "/"))
        self.pbDodaj.setText(_translate("MainWindow", "+"))
        self.pbOdejmij.setText(_translate("MainWindow", "-"))
        self.pbKropka.setText(_translate("MainWindow", "."))
        self.pbClear.setText(_translate("MainWindow", "Clear"))
        self.pb7.setText(_translate("MainWindow", "7"))
        self.pb8.setText(_translate("MainWindow", "8"))
        self.pb9.setText(_translate("MainWindow", "9"))
        self.pb4.setText(_translate("MainWindow", "4"))
        self.pb5.setText(_translate("MainWindow", "5"))
        self.pb6.setText(_translate("MainWindow", "6"))
        self.pb1.setText(_translate("MainWindow", "1"))
        self.pb2.setText(_translate("MainWindow", "2"))
        self.pb3.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

